\echo Starting ATROX PostgreSQL deployment (refactored)
\echo Schema
\i ./Schema/01_Schema.sql
\echo Tables
\i ./Tables/atrox_company.sql
\i ./Tables/atrox_version_status.sql
\i ./Tables/atrox_application.sql
\i ./Tables/atrox_function.sql
\i ./Tables/atrox_role.sql
\i ./Tables/atrox_user.sql
\i ./Tables/atrox_installation.sql
\i ./Tables/atrox_version_event.sql
\i ./Tables/atrox_screen.sql
\i ./Tables/atrox_service.sql
\i ./Tables/atrox_action.sql
\i ./Tables/atrox_screen_version.sql
\i ./Tables/atrox_service_version.sql
\i ./Tables/atrox_action_version.sql
\i ./Tables/atrox_action_parameter.sql
\i ./Tables/atrox_role_function.sql
\i ./Tables/atrox_screen_function.sql
\i ./Tables/atrox_user_role.sql
\i ./Tables/atrox_menu.sql
\i ./Tables/atrox_security_client.sql
\i ./Tables/atrox_current_version_constraints.sql
\echo Indexes
\i ./Indexes/06_Indexes.sql
\echo Functions
\i ./Functions/fn_atrox_next_action_version.sql
\i ./Functions/fn_atrox_next_screen_version.sql
\i ./Functions/fn_atrox_next_service_version.sql
\echo Procedures
\i ./Procedures/company/proc_atrox_company_create.sql
\i ./Procedures/company/proc_atrox_company_get_by_id.sql
\i ./Procedures/company/proc_atrox_company_list.sql
\i ./Procedures/company/proc_atrox_company_soft_delete.sql
\i ./Procedures/company/proc_atrox_company_update.sql
\i ./Procedures/application/proc_atrox_application_create.sql
\i ./Procedures/application/proc_atrox_application_get_by_id.sql
\i ./Procedures/application/proc_atrox_application_list.sql
\i ./Procedures/application/proc_atrox_application_soft_delete.sql
\i ./Procedures/application/proc_atrox_application_update.sql
\i ./Procedures/user/proc_atrox_user_create.sql
\i ./Procedures/user/proc_atrox_user_get_by_id.sql
\i ./Procedures/user/proc_atrox_user_list.sql
\i ./Procedures/user/proc_atrox_user_soft_delete.sql
\i ./Procedures/user/proc_atrox_user_update.sql
\i ./Procedures/role/proc_atrox_role_create.sql
\i ./Procedures/role/proc_atrox_role_get_by_id.sql
\i ./Procedures/role/proc_atrox_role_list.sql
\i ./Procedures/role/proc_atrox_role_soft_delete.sql
\i ./Procedures/role/proc_atrox_role_update.sql
\i ./Procedures/menu/proc_atrox_menu_create.sql
\i ./Procedures/menu/proc_atrox_menu_get_by_id.sql
\i ./Procedures/menu/proc_atrox_menu_list.sql
\i ./Procedures/menu/proc_atrox_menu_soft_delete.sql
\i ./Procedures/menu/proc_atrox_menu_update.sql
\i ./Procedures/screen/proc_atrox_screen_create_version.sql
\i ./Procedures/screen/proc_atrox_screen_create.sql
\i ./Procedures/screen/proc_atrox_screen_disable_version.sql
\i ./Procedures/screen/proc_atrox_screen_enable_version.sql
\i ./Procedures/screen/proc_atrox_screen_get_active_version.sql
\i ./Procedures/screen/proc_atrox_screen_get_by_id.sql
\i ./Procedures/screen/proc_atrox_screen_list.sql
\i ./Procedures/screen/proc_atrox_screen_soft_delete.sql
\i ./Procedures/screen/proc_atrox_screen_update.sql
\i ./Procedures/service/proc_atrox_service_create_version.sql
\i ./Procedures/service/proc_atrox_service_create.sql
\i ./Procedures/service/proc_atrox_service_disable_version.sql
\i ./Procedures/service/proc_atrox_service_enable_version.sql
\i ./Procedures/service/proc_atrox_service_get_active_version.sql
\i ./Procedures/service/proc_atrox_service_get_by_id.sql
\i ./Procedures/service/proc_atrox_service_list.sql
\i ./Procedures/service/proc_atrox_service_soft_delete.sql
\i ./Procedures/service/proc_atrox_service_update.sql
\i ./Procedures/action/proc_atrox_action_create_version.sql
\i ./Procedures/action/proc_atrox_action_create.sql
\i ./Procedures/action/proc_atrox_action_disable_version.sql
\i ./Procedures/action/proc_atrox_action_enable_version.sql
\i ./Procedures/action/proc_atrox_action_get_active_version.sql
\i ./Procedures/action/proc_atrox_action_get_by_id.sql
\i ./Procedures/action/proc_atrox_action_list.sql
\i ./Procedures/action/proc_atrox_action_soft_delete.sql
\i ./Procedures/action/proc_atrox_action_update.sql
\echo Seed
\i ./Seed/09_Seed_Data.sql
\echo ATROX PostgreSQL deployment completed

