PRINT 'Starting ATROX SQL Server deployment (refactored)';
PRINT 'Schema';
:r .\\Schema\\01_Schema.sql
PRINT 'Tables';
:r .\\Tables\\atrox_action.sql
:r .\\Tables\\atrox_action_parameter.sql
:r .\\Tables\\atrox_action_version.sql
:r .\\Tables\\atrox_application.sql
:r .\\Tables\\atrox_company.sql
:r .\\Tables\\atrox_function.sql
:r .\\Tables\\atrox_installation.sql
:r .\\Tables\\atrox_menu.sql
:r .\\Tables\\atrox_role.sql
:r .\\Tables\\atrox_role_function.sql
:r .\\Tables\\atrox_screen.sql
:r .\\Tables\\atrox_screen_function.sql
:r .\\Tables\\atrox_screen_version.sql
:r .\\Tables\\atrox_service.sql
:r .\\Tables\\atrox_service_version.sql
:r .\\Tables\\atrox_user.sql
:r .\\Tables\\atrox_user_role.sql
:r .\\Tables\\atrox_version_event.sql
:r .\\Tables\\atrox_version_status.sql
PRINT 'Indexes';
:r .\\Indexes\\06_Indexes.sql
PRINT 'Functions';
:r .\\Functions\\fn_atrox_next_action_version.sql
:r .\\Functions\\fn_atrox_next_screen_version.sql
:r .\\Functions\\fn_atrox_next_service_version.sql
PRINT 'Procedures';
:r .\\Procedures\\company\\proc_atrox_company_create.sql
:r .\\Procedures\\company\\proc_atrox_company_get_by_id.sql
:r .\\Procedures\\company\\proc_atrox_company_list.sql
:r .\\Procedures\\company\\proc_atrox_company_soft_delete.sql
:r .\\Procedures\\company\\proc_atrox_company_update.sql
:r .\\Procedures\\application\\proc_atrox_application_create.sql
:r .\\Procedures\\application\\proc_atrox_application_get_by_id.sql
:r .\\Procedures\\application\\proc_atrox_application_list.sql
:r .\\Procedures\\application\\proc_atrox_application_soft_delete.sql
:r .\\Procedures\\application\\proc_atrox_application_update.sql
:r .\\Procedures\\user\\proc_atrox_user_create.sql
:r .\\Procedures\\user\\proc_atrox_user_get_by_id.sql
:r .\\Procedures\\user\\proc_atrox_user_list.sql
:r .\\Procedures\\user\\proc_atrox_user_soft_delete.sql
:r .\\Procedures\\user\\proc_atrox_user_update.sql
:r .\\Procedures\\role\\proc_atrox_role_create.sql
:r .\\Procedures\\role\\proc_atrox_role_get_by_id.sql
:r .\\Procedures\\role\\proc_atrox_role_list.sql
:r .\\Procedures\\role\\proc_atrox_role_soft_delete.sql
:r .\\Procedures\\role\\proc_atrox_role_update.sql
:r .\\Procedures\\menu\\proc_atrox_menu_create.sql
:r .\\Procedures\\menu\\proc_atrox_menu_get_by_id.sql
:r .\\Procedures\\menu\\proc_atrox_menu_list.sql
:r .\\Procedures\\menu\\proc_atrox_menu_soft_delete.sql
:r .\\Procedures\\menu\\proc_atrox_menu_update.sql
:r .\\Procedures\\screen\\proc_atrox_screen_create.sql
:r .\\Procedures\\screen\\proc_atrox_screen_create_version.sql
:r .\\Procedures\\screen\\proc_atrox_screen_disable_version.sql
:r .\\Procedures\\screen\\proc_atrox_screen_enable_version.sql
:r .\\Procedures\\screen\\proc_atrox_screen_get_active_version.sql
:r .\\Procedures\\screen\\proc_atrox_screen_get_by_id.sql
:r .\\Procedures\\screen\\proc_atrox_screen_list.sql
:r .\\Procedures\\screen\\proc_atrox_screen_soft_delete.sql
:r .\\Procedures\\screen\\proc_atrox_screen_update.sql
:r .\\Procedures\\service\\proc_atrox_service_create.sql
:r .\\Procedures\\service\\proc_atrox_service_create_version.sql
:r .\\Procedures\\service\\proc_atrox_service_disable_version.sql
:r .\\Procedures\\service\\proc_atrox_service_enable_version.sql
:r .\\Procedures\\service\\proc_atrox_service_get_active_version.sql
:r .\\Procedures\\service\\proc_atrox_service_get_by_id.sql
:r .\\Procedures\\service\\proc_atrox_service_list.sql
:r .\\Procedures\\service\\proc_atrox_service_soft_delete.sql
:r .\\Procedures\\service\\proc_atrox_service_update.sql
:r .\\Procedures\\action\\proc_atrox_action_create.sql
:r .\\Procedures\\action\\proc_atrox_action_create_version.sql
:r .\\Procedures\\action\\proc_atrox_action_disable_version.sql
:r .\\Procedures\\action\\proc_atrox_action_enable_version.sql
:r .\\Procedures\\action\\proc_atrox_action_get_active_version.sql
:r .\\Procedures\\action\\proc_atrox_action_get_by_id.sql
:r .\\Procedures\\action\\proc_atrox_action_list.sql
:r .\\Procedures\\action\\proc_atrox_action_soft_delete.sql
:r .\\Procedures\\action\\proc_atrox_action_update.sql
PRINT 'Seed';
:r .\\Seed\\09_Seed_Data.sql
PRINT 'ATROX SQL Server deployment completed';

