DO $do$
BEGIN
    CREATE SCHEMA IF NOT EXISTS ATROX;
    RAISE NOTICE '<<<CREATED SCHEMA ATROX.ATROX>>>';
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE '<<<FAILED CREATING SCHEMA ATROX.ATROX>>>';
END
$do$;