BEGIN TRY
    IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'ATROX')
    BEGIN
        EXEC('CREATE SCHEMA ATROX');
    END;

    PRINT '<<<CREATED SCHEMA ATROX.ATROX>>>';
END TRY
BEGIN CATCH
    PRINT '<<<FAILED CREATING SCHEMA ATROX.ATROX>>>';
END CATCH;